services:
  frontend:
    build: ./frontend
    image: frontend-image
    container_name: frontend-container
    ports:
      - "5137:5137"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    image: backend-image
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
